### PR TITLE
Update to v0.1.3

### PR DESCRIPTION
**Pull request by dbrgn**

### CODE REVIEW

**Comment by dbrgn** [comment]
Hm, ok, it was worth a try :slightly_smiling_face: The patch probably needs to be updated.

@ubruhin do you have a good workflow to generate that patch, or did you do it manually?

Maybe you want to update the metadata / description anyways, so I guess it's probably better if you do the change directly.

**Comment by ubruhin** [comment]
> The patch probably needs to be updated.

I think you just forgot to update the Git commit hash of the 0.1.3 tag :wink: And btw, the release date is "slightly" wrong :grin:

> @ubruhin do you have a good workflow to generate that patch, or did you do it manually?

Hmm probably it would make sense to update that file in the LibrePCB repo *before* creating new releases, then we don't have to patch it at all... I think I'll add this to the release checklist.

**Comment by dbrgn** [comment]
No, the problem is still the patch :slightly_smiling_face: 

```
patching file share/metainfo/org.librepcb.LibrePCB.appdata.xml
Hunk #3 FAILED at 49.
1 out of 3 hunks FAILED -- saving rejects to file share/metainfo/org.librepcb.LibrePCB.appdata.xml.rej
```

I'll update the patch.

**Comment by dbrgn** [comment]
Finally :slightly_smiling_face: 

I tested the build, seems to work properly!

**Comment by ubruhin** [comment]
Perfect, thanks! :tada:

**Pull request merged**
