### PR TITLE
Update runtime to 5.15-21.08

### PR DESCRIPTION
**Pull request by eduardosm**

### CODE REVIEW

**Comment by ubruhin** [comment]
Thanks @eduardosm !

Just out of curiosity, is there any specific reason for this update? How did you actually know there's an update available? Somehow I'm not able to find any official information about which versions are available, a changelog or something like that...

**Comment by eduardosm** [comment]
> Just out of curiosity, is there any specific reason for this update?

Mostly for the sake of using the latest runtime version.

> How did you actually know there's an update available?

I was told so when I submitted an app to flathub.

The only place where I found some information about available versions is the branch list of the [runtime repository](https://invent.kde.org/packaging/flatpak-kde-runtime).

**Comment by hfiguiere** [comment]
basically every august there is a new freedesktop-sdk and following there is a kde sdk update. The updated GNOME sdk come when they release.

And 20.08 upon which the kde 5.15 sdk is based one will be EOL in August 2022 (two years)

The releases should be communicated better.

**Comment by ubruhin** [comment]
Alright, thanks for the clarification! :)

**Pull request merged**
