### PR TITLE
Update org.kde.Sdk to version 6.7

### PR DESCRIPTION
**Pull request by Alexander-Wilms**

### CODE REVIEW

**Comment by Alexander-Wilms** [comment]
Currently, the opencascade build fail with this error:

```
[5343/5353] Generating OCCT overview documentation with Doxygen
FAILED: doc/overview/html/occt_logo.png /run/build/opencascade/_flatpak_build/doc/overview/html/occt_logo.png 
cd /run/build/opencascade/_flatpak_build/doc && /usr/bin/doxygen /run/build/opencascade/_flatpak_build/doc/occt.cfg
warning: Tag 'HTML_TIMESTAMP' at line 41 of file '/run/build/opencascade/_flatpak_build/doc/occt.cfg' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'FORMULA_TRANSPARENT' at line 52 of file '/run/build/opencascade/_flatpak_build/doc/occt.cfg' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
/usr/include/c++/13.2.0/string_view:258: constexpr const std::basic_string_view<_CharT, _Traits>::value_type& std::basic_string_view<_CharT, _Traits>::operator[](size_type) const [with _CharT = char; _Traits = std::char_traits<char>; const_reference = const char&; size_type = long unsigned int]: Assertion '__pos < this->_M_len' failed.
[5344/5353] Building CXX object src/TKExpress/CMakeFiles/TKExpress.dir/__/Express/Express_Entity.cxx.o
[5345/5353] Building CXX object src/TKStd/CMakeFiles/TKStd.dir/__/ShapePersistent/ShapePersistent.cxx.o
ninja: build stopped: subcommand failed.
```

**Comment by hfiguiere** [comment]
Looks like a bug in the code triggered by the fact that for safety reasons we build with CXX_ASSERTIONS on.

**Comment by ubruhin** [comment]
Two quick comments from my side:

- My comment https://github.com/flathub/org.librepcb.LibrePCB/pull/17#issuecomment-2089674497 still applies: LibrePCB has still some issues with Qt6 which are fixed in the mean time but no release is made yet. So I highly prefer to wait with this PR until a new release is available.
- We didn't test OCCT 7.8.1 yet and in my experience OpenCascade behaves very different depending on its version (sometimes show-stopping bugs!). I really don't like to receive LibrePCB bug reports caused by OpenCascade bugs, thus we now ship all our LibrePCB releases with the known working version 7.7.2. I know many people want to be bleeding edge all the time, I prefer stability, so maybe we could stick with 7.7.2 for now? :wink:

**Comment by Alexander-Wilms** [comment]
Yes, the MR is only meant for testing, so issues can be caught early.

 I tried to report the OCCT issue at https://tracker.dev.opencascade.org/view_all_bug_page.php , but didn't get to it yet since I can't register.

**Comment by ubruhin** [comment]
Alright, perfect then! :+1: Thanks.

**Comment by ubruhin** [comment]
> Looks like a bug in the code triggered by the fact that for safety reasons we build with CXX_ASSERTIONS on.

> I tried to report the OCCT issue at https://tracker.dev.opencascade.org/view_all_bug_page.php , but didn't get to it yet since I can't register.

For the record, the problem seems to be in Doxygen, not in OCCT. #28 fixed the build error as we don't need to run Doxygen.

**Pull request closed without merging**
