### PR TITLE
Version 0.1.4, remove patch, upgrade runtime to 5.14

### PR DESCRIPTION
**Pull request by dbrgn**

### CODE REVIEW

**Comment by dbrgn** [comment]
@ubruhin it seems that the 0.1.4 tag points to the wrong commit?

**Comment by dbrgn** [comment]
I only did a few small checks, but it seems to work fine.

**Comment by dbrgn** [comment]
@ubruhin you'll have to merge yourself, I don't have any permissions here.

**Comment by ubruhin** [comment]
Hmm okay, unfortunately I can't manage permissions of this repository :sob: But OK, at least I can merge :)

**Pull request merged**
