### PR TITLE
Update to LibrePCB 1.0.0

### PR DESCRIPTION
**Pull request by Alexander-Wilms**

### CODE REVIEW

**Comment by ubruhin** [comment]
@Alexander-Wilms btw, did you see my comment https://github.com/flathub/org.librepcb.LibrePCB/pull/14#issuecomment-1688717081?

Just let me know if I should take over the integration of OpenCascade into the Flatpak. It would be a shame not having full 3D support in the Flatpak :)

**Comment by Alexander-Wilms** [comment]
Ah, I missed that comment. I had taken a quick look at OpenCascade and it seemed like one needed to register in order to download the source archive.

I'll add the module, but I can't test it right now.

**Comment by ubruhin** [comment]
> I had taken a quick look at OpenCascade and it seemed like one needed to register in order to download the source archive.

Yeah I had the same feeling but then I found the public sources on GitHub :grin: Works fine with the download/build/install commands provided in our Dockerfile.

> I'll add the module, but I can't test it right now.

Great! I think I could try it when the build is ready.

**Comment by Alexander-Wilms** [comment]
@ubruhin The build is ready for testing

**Comment by ubruhin** [comment]
I quickly tested build 44446 on x86_64, so far it looks good to me!

Only the 3D viewer has some ugly rendering artifacts, but I experienced this issue also without Flatpak. Seems to happen when running natively on Wayland :slightly_frowning_face:

**Comment by Alexander-Wilms** [comment]
Hm, you could try if `flatpak run --nosocket=wayland org.librepcb.LibrePCB//test` works around the issue to confirm your suspicion.

**Comment by ubruhin** [comment]
> Hm, you could try if flatpak run --nosocket=wayland org.librepcb.LibrePCB//test works around the issue to confirm your suspicion.

Ah, that's nice! Yes it fixes the problem indeed, rendering is perfect with this workaround.

There are other issues on Wayland anyway. At least the window switching with the menu/toolbar entries "Control Panel", "Schematic Editor" and "Board Editor" do not work on Wayland (Qt prints a warning that this is not implemented on Wayland). Due to these things we explicitly disable Wayland in our Snap package. I don't know if we should do the same with Flatpak, it's quite ugly.

**Comment by ubruhin** [comment]
Another problem is that window positions are not saved/restored on Wayland. This is very annoying when using LibrePCB productively. When disabling Wayland, it works as expected.

**Comment by Alexander-Wilms** [comment]
Yes, I think there are no real downsides to disabling Wayland for now.

**Comment by dbrgn** [comment]
@Alexander-Wilms version 1.0.0 is out now! https://librepcb.org/blog/2023-09-24_release_1.0.0/

**Comment by ubruhin** [comment]
Thanks for updating @Alexander-Wilms! I quickly tested the build, looks good to me :+1: 

So we can now merge and release this, right?

**Comment by Alexander-Wilms** [comment]
@ubruhin Yes. I've also added data so the modules get updated automatically to the latest stable release:

https://release-monitoring.org/project/154259/

**Comment by ubruhin** [comment]
Published! :muscle:  https://flathub.org/apps/org.librepcb.LibrePCB

**Pull request merged**
