### PR TITLE
Update to version 1.0.0-rc1

### PR DESCRIPTION
**Pull request by Alexander-Wilms**

### CODE REVIEW

**Comment by ubruhin** [comment]
Hi @Alexander-Wilms,
thanks for picking this up! :slightly_smiling_face: 

I just want to mention that generally my intention is not to publish the current release candidate on FlatHub since as a user I'd expect receiving only stable releases. In contrast to Snap, it seems on Flathub we don't have different release channels (I read something about FlatHub Beta, but I don't know how to publish apps there). So I'd suggest to wait with the update until the stable release is out.

**Comment by Alexander-Wilms** [comment]
Yes, I didn't intend to publish the RC, but get the manifest ready and use the buildbot to test it.

Apropos: Could you update the metainfo file?

```
builddir/files/share/appdata/org.librepcb.LibrePCB.appdata.xml: FAILED:
• file-invalid          : <screenshot> failed to load [https://docs.librepcb.org/about/img/screenshot.png]
• file-invalid          : <screenshot> failed to load [https://librepcb.org/img/board_editor.png]
• file-invalid          : <screenshot> failed to load [https://librepcb.org/img/control_panel.png]
• file-invalid          : <screenshot> failed to load [https://librepcb.org/img/thumbs/add_component_dialog.png]
• file-invalid          : <screenshot> failed to load [https://librepcb.org/img/library_manager.png]
• file-invalid          : <screenshot> failed to load [https://librepcb.org/img/schematic_editor.png]
Validation of files failed
```

**Comment by ubruhin** [comment]
> Yes, I didn't intend to publish the RC, but get the manifest ready and use the buildbot to test it.

Ah, perfect! :+1:

> Apropos: Could you update the metainfo file?

Hm actually I updated it for 1.0.0-rc1: https://github.com/LibrePCB/LibrePCB/blob/1.0.0-rc1/share/metainfo/org.librepcb.LibrePCB.appdata.xml

**Comment by Alexander-Wilms** [comment]
Sorry, I got the two PRs confused. One still used the old tag, this is the correct PR: https://github.com/flathub/org.librepcb.LibrePCB/pull/15

The x86_64 build succeeded, the aarch64 build did not.

**Comment by ubruhin** [comment]
> The x86_64 build succeeded, the aarch64 build did not.

Alright, I'll check how we can fix the compile error for the stable release.

Btw, I saw you currently disabled OpenCascade. Would be nice if we can build with OpenCascade of course. Probably we need to build it by ourselves, right? For reference, here's how we build OpenCascade for our official binary releases:

https://github.com/LibrePCB/docker-librepcb-dev/blob/eb077a5a7e7f3ab1ff2cf30bf866fd98edb6a0c5/ubuntu-18.04-qt5.15.2/Dockerfile#L73-L101

**Pull request closed without merging**
